# Generated by Django 5.2.4 on 2025-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
